#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/12/8 21:36
# @Author  : David
# @email   : mingren4792@126.com
# @File    : config.py

LOGOGRAM = {
        'nvr': 'never',
        'uhh': 'you',
        'uh': 'you',
        'phn': 'phone',
        'jst ': 'just',
        'cz': 'because',
        'aint': 'am not',
        'nw': 'now',
        'srry': 'sorry',
        'pic': 'picture',
        'snd': 'send',
        'ppls': 'please',
        'whn': 'when',
        'nthing': 'nothing',
        'samting': 'somthing',
        'dnot':'do not',
        'thankyou':'thank you',
        'frnd': 'friend',
        'qstn': 'question',
        "nthng": 'nothing',
        "whatsup": 'what is up',
        'thnxx': 'thanks',
        'thnx': 'thanks',
        "hppnd": 'happend',
        "isfor": 'is for',
        "wasn't": 'was not',
        'havent': 'have not',
        "replyme": 'reply me',
        "iscomputer": 'is computer',
        "whatsapp": 'what is application',
        'didnt': "did not",
        "thanx": 'thanks',
        "you've": 'you have',
        "ain't": 'can not',
        'nufn': 'nothing',
        "&":'and',
        "dn": 'do not',
        "nd": 'end',
        "doesn't": 'dose not',
        "i'm": 'i am',
        "aren't": 'are not',
        'wont': 'will not',
        'isnt': 'is not',
        'wht': 'what',
        "ur's": 'your is',
        'tme': 'time',
        'lol': 'laugh out loud',
        'slp': 'sleep',
        'tym': 'time',
        'wat': 'what',
        'hv': 'have',
        'ntng': 'nothing',
        "we're": 'we are',
        "plzz": 'please',
        "arn't": 'are not',
        'arnt': 'are not',
        'wouldnt': 'would not',
        "wouldn't": 'would not',
        'shouldnt': 'should not',
        "shouldn't": 'should not',
        "couldn't": 'could not',
        "couldnt": 'could not',
        "it'll": "it will",
        "itll": 'it will',
        "whats": 'what is',
        "she's": 'she is',
        'shes': 'she is',
        "he's": 'he is',
        'hes': 'he is',
        "how's": 'how is',
        'hows': 'how is',
        "nt": 'nothing',
        "isn't":'is not',
        "dont":"do not",
        "when's":'when is',
        'whens':'when is',
        "there's":'there is',
        'its':'it is',
        "can't":"can not",
        "let's":'let us',
        'lets':'let us',
        "i've":'i have',
        'ive':'i have',
        "that's":'that is',
        'thats':'that is',
        "won't": 'will not',
        "what's": 'what is',
        "dosen't": 'dose not',
        'dosent':'dose not',
        "you're":'you are',
        'youre':'you are',
        "didn't":'did not',
        "i'll":'i will',
        "you'll":'you will',
        "youll":'you will',
        "it's":'it is',
        "don't":'do not',
        "i'm":'i am',
        'dnt':'do not',
        'frnds':'friends',
        'bday':'birthday',
        'wr':'where',
        'wt':'what',
        'wtf':'What the fuck',
        'pl':'please',
        'hw':'how',
        'coz':'because',
        'bcz': 'because',
        'cuz':'cause',
        'Idk':'i do not know',
        'idk':'i do not know',
        'bt':'but',
        'abt':'about',
        'bcoz':'because',
        'im':'i am',
        'U':'you',
        'r':'are',
        'R': 'are',
        'gf':'girlfriend',
        'bf':'boyfriend',
        'u':'you',
        'Ur':'Your',
        'wlcm':'Wellcome',
        'm8':'mate',
        'mgmt':'management',
        'mmfu':'my mate fancies you',
        'mob':'mobile',
        'msg':'message ',
        'msia':'malaysia',
        'mtfbwu':'may the force be with you',
        'mtg':'meeting',
        'mth':'month',
        'myob':'mind your own business',
        'n/a':'not applicable',
        'ne':'any',
        'ne1':'anyone',
        'nethng':'anything',
        'no1':'no one',
        'np':'no problem',
        'nvm':'never mind',
        'oic':'oh, i see',
        'omg':'oh, my god',
        'paw':'parents are watching',
        'pcm':'please call me',
        'pls':'please',
        'plz':'please',
        'plz4gvme':'please forgive me',
        'po$bl':'possible',
        'ppl':'people',
        'prl':'parents are listening',
        'puks':'pick up kids',
        'rgds':'regards',
        'ringl8':'running late',
        'rtfm':'read the flippin manual',
        'ru':'are you',
        'cmng':'coming',
        'ruok':'are you okay?',
        'shopn':'shopping',
        'sit':'stay in touch',
        'soz':'sorry',
        'spk':'speak',
        'stfu':'shut the flip up',
        'sum1':'someone',
        'tel':'telephone',
        'thanq':'thank you',
        'thkq':'thank you',
        'thx':'thanks',
        'tmb':'text me back',
        'tq':'thank you',
        'ttyl':'talk to you later',
        'tx':'thanks',
        'tyvm':'thank you very much',
        'u':'you',
        'ur':'your',
        'ura*':'you are a star',
        'uraqt':'you are a cutie',
        'w/':'with',
        'w/o':'without',
        'w8':'wait',
        'w84m':'wait for me',
        'wan2':'want to',
        'wan2tlk':'want to talk?',
        'wbs':'with',
        'wearing':'a walkman',
        'wel':'well',
        'wiv':'write back soon',
        'wknd':'weekend',
        'wot':'what',
        'wru':'where are you?',
        'wu':"what's up?",
        'wud?':'what you doing',
        'wygowm':'will you go out with me',
        'x':'kiss',
        'xlnt':'excellent',
        'xoxox':'hugs and kisses',
        'y':'why',
        'yr':'your',
        'yyssw':'yeah yeah sure sure whatever',
        '1ce':'once',
        '2':'to',
        '26y4u':'too sexy for you',
        '2day':'today',
        '2mor':'tomorrow',
        '2nite':'tonight',
        '3sum':'threesome',
        '4':'for',
        '911':'emergency - call me',
        'aka':'also known as',
        'asap':'as soon as possible',
        'atb':'all the best',
        'b':'be',
        'b4':'before',
        'b4n':'or bfn bye for now',
        'bbl':'be back later',
        'bcnu':'be seeing you',
        "b'day":'birthday',
        'bhl8':'be home late',
        'bil':'boss is listening',
        'brb':'be right back',
        'btdt':'been there done that',
        'btw':'by the way',
        'buzz':'off buzz off',
        'c':'see',
        'cid':'consider it done',
        'cmi':'call me',
        'ctr':'center',
        'cu':'see you',
        'cubl8r':'call you back later',
        'cul':'see you later',
        'cyr':'call your',
        'bos':'boss',
        'bro':'brother',
        'ma':'mother',
        'ofis':'office',
        'pa':'father',
        'wf':'wife',
        'don':'doing',
        'dylm':'do you like me',
        'ez':'easy',
        'f2f':'face to face',
        'f2t':'free to talk',
        'fotflol':'falling on the floor, laughing out loud',
        'fyi':'for your in from ation',
        'gal':'get a life',
        'grt':'great',
        'gtg':'got to go',
        'gudluk':'good luck',
        'h8':'hate',
        'hak':'hugs and kisses',
        'hand':'have a nice day',
        'hot4u':'hot for you',
        'hp':'handphone',
        'ic':'i see',
        'iluvu':'i love you',
        'im2gud4u':"i'm too good for you",
        'imho':'in my humble opinion',
        'imnsho':'in my not so humble opinion',
        'imtng':'in meeting',
        'iyq':'i like you',
        'jk':'just kidding',
        'jhb':'johannesburg',
        'jic':'just in case',
        'jk':'just kdding',
        'kit':'keep in touch',
        'kwim':'know what i mean',
        'l8':'late',
        'l8r':'later',
        'ldn':'london',
        'lol':'laughing out loud or loads of love',
        'lv':'love',
        'lying':'lyn'
}


EMOTICONS_TOKEN = {
    '>_>': '<doubt>',
    '-_-': '<indifference>',
    '(^_^)':'<smile>',
    ':*': '<kiss>',
    ':-*': '<kiss>',
    ':x': '<kiss>',
    ':-)': '<happy>',
    ':-))': '<happy>',
    ':-)))': '<happy>',
    ':-))))': '<happy>',
    ':-)))))': '<happy>',
    ':-))))))': '<happy>',
    ':)': '<happy>',
    ':))': '<happy>',
    ':)))': '<happy>',
    ':))))': '<happy>',
    ':)))))': '<happy>',
    ':))))))': '<happy>',
    ':)))))))': '<happy>',
    ':o)': '<happy>',
    ':]': '<happy>',
    ':3': '<happy>',
    ':c)': '<happy>',
    ':>': '<happy>',
    '=]': '<happy>',
    '8)': '<happy>',
    '=)': '<happy>',
    ':}': '<happy>',
    ':^)': '<happy>',
    '|;-)': '<happy>',
    ":'-)": '<happy>',
    ":')": '<happy>',
    '\o/': '<happy>',
    '*\\0/*': '<happy>',
    ':-D': '<laugh>',
    ':D': '<laugh>',
    # '(\':': '<laugh>',
    '8-D': '<laugh>',
    '8D': '<laugh>',
    'x-D': '<laugh>',
    'xD': '<laugh>',
    'X-D': '<laugh>',
    'XD': '<laugh>',
    '=-D': '<laugh>',
    '=D': '<laugh>',
    '=-3': '<laugh>',
    '=3': '<laugh>',
    'B^D': '<laugh>',
    '>:[': '<sad>',
    ':-(': '<sad>',
    ':-((': '<sad>',
    ':-(((': '<sad>',
    ':-((((': '<sad>',
    ':-(((((': '<sad>',
    ':-((((((': '<sad>',
    ':-(((((((': '<sad>',
    ':(': '<sad>',
    ':((': '<sad>',
    ':(((': '<sad>',
    ':((((': '<sad>',
    ':(((((': '<sad>',
    ':((((((': '<sad>',
    ':(((((((': '<sad>',
    ':((((((((': '<sad>',
    ':-c': '<sad>',
    ':c': '<sad>',
    ':-<': '<sad>',
    ':<': '<sad>',
    ':-[': '<sad>',
    ':[': '<sad>',
    ':{': '<sad>',
    ':-||': '<sad>',
    ':@': '<sad>',
    ":'-(": '<sad>',
    ":'(": '<sad>',
    'D:<': '<sad>',
    'D:': '<sad>',
    'D8': '<sad>',
    'D;': '<sad>',
    'D=': '<sad>',
    'DX': '<sad>',
    'v.v': '<sad>',
    "D-':": '<sad>',
    '(>_<)': '<sad>',
    ':|': '<sad>',
    '>:O': '<surprise>',
    ':-O': '<surprise>',
    ':-o': '<surprise>',
    ':O': '<surprise>',
    '°o°': '<surprise>',
    'o_O': '<surprise>',
    'o_0': '<surprise>',
    'o.O': '<surprise>',
    'o-o': '<surprise>',
    '8-0': '<surprise>',
    '|-O': '<surprise>',
    ';-)': '<wink>',
    ';)': '<wink>',
    '*-)': '<wink>',
    '*)': '<wink>',
    ';-]': '<wink>',
    ';]': '<wink>',
    ';D': '<wink>',
    ';^)': '<wink>',
    ':-,': '<wink>',
    '>:P': '<tong>',
    ':-P': '<tong>',
    ':P': '<tong>',
    'X-P': '<tong>',
    'x-p': '<tong>',
    'xp': '<tong>',
    'XP': '<tong>',
    ':-p': '<tong>',
    ':p': '<tong>',
    '=p': '<tong>',
    ':-Þ': '<tong>',
    ':Þ': '<tong>',
    ':-b': '<tong>',
    ':b': '<tong>',
    ':-&': '<tong>',
    '>:\\': '<annoyed>',
    '>:/': '<annoyed>',
    ':-/': '<annoyed>',
    ':-.': '<annoyed>',
    ':/': '<annoyed>',
    ':\\': '<annoyed>',
    '=/': '<annoyed>',
    '=\\': '<annoyed>',
    ':L': '<annoyed>',
    '=L': '<annoyed>',
    ':S': '<annoyed>',
    '>.<': '<annoyed>',
    ':-|': '<annoyed>',
    '<:-|': '<annoyed>',
    '>:(': '<annoyed>',
    ":-\\": '<anger>',
    ':-X': '<seallips>',
    ':X': '<seallips>',
    ':-#': '<seallips>',
    ':#': '<seallips>',
    'O:-)': '<angel>',
    '0:-3': '<angel>',
    '0:3': '<angel>',
    '0:-)': '<angel>',
    '0:)': '<angel>',
    '0;^)': '<angel>',
    '>:)': '<devil>',
    '>:D': '<devil>',
    '>:-D': '<devil>',
    '>;)': '<devil>',
    '>:-)': '<devil>',
    '}:-)': '<devil>',
    '}:)': '<devil>',
    '3:-)': '<devil>',
    '3:)': '<devil>',
    'o/\o': '<highfive>',
    '^5': '<highfive>',
    '>_>^': '<highfive>',
    '^<_<': '<highfive>',  # todo:fix tokenizer - MISSES THIS
    '<3': '<heart>',
    '^-^': '<smile>',
    '(^ . ^)': '<happpy>',
    '(:': '<happy>',
    '(^○^)': '<lovly>',
}

TWEMOJI_LIST = ['😍', '😁', '😭', '😑', '😢', '👍', '😀', '🙂', '😓', '😒', '😂', '💔', '😪', '😞', '😔',
                '😉', '😆', '😩','👍🏻', '😲', '😃', '😲', '😚', '❤', '😼', '😬', '😺', '😸', '✌', '😿',
                '😊', '🤗', '💗', '😘', '😽', '😌', '😠', '😏', '😟', '😿', '✈', '😹', '💕', '❤', '🙏',
                '☕', '🍺', '☹', '😤', '👏', '🙁', '😶', '😦', '🙈', '⚽', '👄', '💋', '🌹', '⚘', '😎',
                '😧', '😕', '😋', '😜', '👌', '🤣', '👼', '👬', '💖', '🐠', '💓', '😡', '🙄', '💃', '😇',
                '🤒', '😷', '😅', '😄', '😥', '😱', '😻', '🙀', '💝', '💛', '👫', '💩', '🙇', '😣', '♥',
                '🙌', '💀', '💑', '😝', '📞', '☎', '☏', '🤓', '👎', '👑', '🙌', '😫', '😾', '😛', '👚',
                '👢', '👖', '🤦', '💪', '😯', '👊', '😨'
                ]

TWEMOJI = {
    '😍': ['Smiling Face With Heart-Eyes', 'conveys enthusiastic feelings of love, infatuation, and adoration'],
    '😁': ['Beaming Face With Smiling Eyes', 'expresses a radiant, gratified happiness'],
    '😭': ['Loudly Crying Face', 'convey inconsolable grief but also other intense feelings, such as uncontrollable'
                                 ' laughter or overwhelming joy'],
    '😑': ['Expressionless Face', 'convey a sense of frustration or annoyance more intense than suggested'],
    '😢': ['Crying Face', 'convey a moderate degree of sadness or pain'],
    '👍': ['Thumbs Up', 'thumbs-up gesture indicating approval'],
    '😀': ['Grinning Face', 'conveys general pleasure and good cheer or humor'],
    '🙂': ['Slightly Smiling Face', ' Conveys a wide range of positive, happy, and friendly sentiments'],
    '😓': ['Downcast Face With Sweat', 'A face with a sad or neutral mouth, with a single drop of sweat'],
    '😒': ['Unamused Face', 'express dissatisfaction'],
    '😂': ['Face With Tears of Joy', 'show something is funny or pleasing'],
    '💔': ['Broken Heart', 'Broken Heart'],
    '😪': ['Sleepy Face', 'character is tired or sleeping in anime or manga'],
    '😞': ['Disappointed Face', 'Disappointed Face'],
    '😔': ['Pensive Face', 'things all went wrong'],
    '😆': ['Grinning Squinting Face', 'conveys excitement or hearty laughter'],
    '😉': ['Winking Face', 'Winking Face'],
    '😩': ['Weary Face', 'given up'],
    '👍🏻': ['Thumbs Up', 'thumbs-up gesture indicating approval'],
    '😃': ['Grinning Face With Big Eyes', 'onveys general happiness and good-natured amusement'],
    '😲': ['Astonished Face', 'shock or surprise'],
    '😚': ['Kissing Face With Closed Eyes', ' conveys sentiments of romantic love and affection'],
    '❤': ['Red Heart', ' expressions of love'],
    '😼': ['Cat Face With Wry Smile', 'Cat Face With Wry Smile'],
    '😬': ['Grimacing Face', 'represent a range of negative or tense emotions'],
    '😺': ['Grinning Cat Face', 'Grinning Cat Face'],
    '😸': ['Grinning Cat Face With Smiling Eyes', 'Grinning Cat Face With Smiling Eyes'],
    '✌' : ['Victory Hand', 'Victory Hand'],
    '😿': ['Crying Cat Face', 'Crying Cat Face'],
    '😊': ['Smiling Face With Smiling Eyes', 'expresses genuine happiness and warm, positive feelings'],
    '🤗': ['Hugging Face', 'Hugging Face'],
    '💗': ['Growing Heart', 'Growing Heart'],
    '😘': ['Face Blowing a Kiss', 'represent a kiss goodbye or good night and convey '
                                  'feelings of love and affection more generally'],
    '😽': ['Kissing Cat Face', 'Kissing Cat Face'],
    '😌': ['Relieved Face', 'convey a calm or content state of mind'],
    '😠': ['Angry Face', 'Conveys varying degrees of anger, from grumpiness and irritation to disgust and outrage'],
    '😏': ['Smirking Face', ' convey flirtation or sexual innuendo'],
    '😟': ['Worried Face', 'Worried Face'],
    '😿': ['Crying Cat Face', 'Crying Cat Face'],
    '✈': ['Airplane', 'Airplane'],
    '😹': ['Cat Face With Tears of Joy', 'Cat Face With Tears of Joy'],
    '💕': ['Two Hearts', 'love is in the air'],
    '❤': ['Red Heart', 'Red Heart'],
    '🙏': ['Folded Hands', ' gesture as praying hands'],
    '☕': ['Hot Beverage', 'Hot Beverage'],
    '🍺': ['Beer Mug', 'Beer Mug'],
    '☹': ['Frowning Face', 'convey such feelings as moderate concern or disappointment and affectionate sadness'],
    '😤': ['Face With Steam From Nose', 'representing frustration at a situation'],
    '👏': ['Clapping Hands', 'as a round of applause'],
    '🙁': ['Slightly Frowning Face', 'conveys a mild degree of concern, disappointment, or sadness'],
    '😶': ['Face Without Mouth', 'conveys speechlessness, humility, and silence'],
    '😦': ['Frowning Face With Open Mouth', 'Frowning Face With Open Mouth'],
    '🙈': ['See-No-Evil Monkey', 'see no evil, hear no evil, speak no evil'],
    '⚽': ['Soccer Ball', 'Soccer Ball'],
    '👄': ['Mouth', 'Mouth'],
    '💋': ['Kiss Mark', 'Kiss Mark'],
    '🌹': ['Flower', 'Flower'],
    '⚘': ['Flower', 'Flower'],
    '😎': ['Smiling Face With Sunglasses', 'convey the slang sense of cool'],
    '😧': ['Anguished Face', 'Anguished Face'],
    '😕': ['Confused Face', ' a bit confused and puzzled by the situation'],
    '😋': ['Face Savoring Food', 'convey that a food item is delicious'],
    '😜': ['Winking Face With Tongue', 'Used in an attempt to be wacky, zany, or otherwise joking'],
    '👌': ['OK Hand', 'I am okay, good yes correct'],
    '🤣': ['Rolling on the Floor Laughing', 'conveys hysterical laughter more intense'],
    '👼': ['Baby Angel', 'Baby Angel'],
    '👬': ['Two Men Holding Hands', 'Two Men Holding Hands'],
    '💖': ['Sparkling Heart', 'Sparkling Heart'],
    '🐠': ['Tropical Fish', 'Tropical Fish'],
    '💓': ['Beating Heart', 'Beating Heart'],
    '😡': ['Pouting Face', 'convey more intense degrees of anger'],
    '🙄': ['Face With Rolling Eyes', 'conveys moderate disdain, disapproval, frustration, or boredom'],
    '💃': ['Woman Dancing', 'represent a sense of fun or as a positive affirmation'],
    '😇': ['Smiling Face With Halo', 'represents angels, prayers, and blessings'],
    '🤒': ['Face With Thermometer', 'represent a hospital patient or person with a cold or flu'],
    '😷': ['Face With Medical Mask', 'avoid sickness or spreading airborne diseases'],
    '😅': ['Grinning Face With Sweat', 'depict nerves or discomfort'],
    '😄': ['Grinning Face With Smiling Eyes', 'conveys general happiness and good-natured amusement'],
    '😥': ['Sad but Relieved Face', 'Sad but Relieved Face'],
    '😱': ['represent horror and fright', 'represent horror and fright'],
    '😻': ['Smiling Cat Face With Heart-Eyes', 'Smiling Cat Face With Heart-Eyes'],
    '🙀': ['Weary Cat Face', 'Weary Cat Face'],
    '💝': ['Heart With Ribbon', 'Heart With Ribbon'],
    '💛': ['Yellow Heart', 'Yellow Heart'],
    '👫': ['Man and Woman Holding Hands', 'Man and Woman Holding Hands'],
    '💩': ['Pile of Poo', 'Pile of Poo'],
    '🙇': ['Person Bowing', 'Person Bowing'],
    '🏻': ['Light Skin Tone', 'Light Skin Tone'],
    '😣': ['Persevering Face', 'Persevering Face'],
    '♥': ['Heart Suit', 'Heart Suit'],
    '🙌': ['Raising Hands', 'Raising Hands'],
    '💀': ['Skull', 'Skull'],
    '💑': ['Couple With Heart', 'Couple With Heart'],
    '☎': ['phone', 'phone'],
    '☏': ['phone', 'phone'],
    '📞': ['Telephone Receiver', 'Telephone Receiver'],
    '😝': ['Squinting Face With Tongue', 'Squinting Face With Tongue'],
    '🤓': ['Nerd Face', 'Nerd Face'],
    '👎': ['Thumbs Down', 'Thumbs Down'],
    '👑': ['Crown', 'Crown'],
    '🙌': ['Raising Hands', 'Raising Hands'],
    '😫': ['Tired Face', 'Tired Face'],
    '😾': ['Pouting Cat Face', 'Pouting Cat Face'],
    '😛': ['being jovial and not serious', 'being jovial and not serious'],
    '👚': ['Woman Clothe', 'Woman Clothe'],
    '👢': ['Woman Boot', 'Woman Boot'],
    '👖': ['Jeans', 'Jeans'],
    '🤦': ['Hitting Head', 'Hitting Head'],
    '💪': ['Strong', 'Strong'],
    '😯': ['Surprise', 'Surprise'],
    '👊': ['Oncoming Fist', 'Oncoming Fist'],
    '😨': ['Fearful Face', 'Fearful Face']
    }